title: BESFEM
description: Battery Electrode Simulation Finite Electrode Method
theme: just-the-docs

url: "https://trahman64.github.io"
baseurl: "/BESFEM_WEBSITE"
aux_links:
  GitHub Repository: https://github.com/HCY-Group/BESFEM